### ISSUE TITLE
Try Opal: print does not work

### ISSUE THREAD

**Issue by vais** [opal/opalrb.org#11]
Enter `print 'hello'` into Try Opal, and it outputs nothing ([here's a link)](http://opalrb.org/try/?code:print%20%27hello%27%0A%20%20). Or is this some sort of limitation of Opal (or Try Opal specifically) that I am simply not aware of?

**Comment by vais** [comment]
Oh, I see now - it is printing to the console because `print` is not overridden the way `puts` is in https://github.com/opal/opalrb.org/blob/master/source/javascripts/try_opal.rb#L92
```
Document.ready? do
  def $stdout.puts(*strs)
    strs.each { |str| TryOpal.instance.print_to_output str }
  end

  TryOpal.instance.run_code
end
```
Should this be fixed?

**Comment by adambeynon** [comment]
Yes, it needs to be. We should probably make it less hacky, and use the IO methods directly: https://github.com/opal/opal/blob/master/opal/corelib/io.rb#L14-L19 .

Something like:

```ruby
Document.ready? do
  $stdout.write_proc = proc { |str| TryOpal.instance.print_to_output str }

  #...
end
```

**Comment by elia** [comment]
:+1:

**Comment by vais** [comment]
@elia @adambeynon I made a new PR to fix this issue based on your feedback and with a clean commit history :)
